-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '{{colors.background.dark.hex}}',
  base01 = '{{colors.surface_container_lowest.dark.hex}}',
  base02 = '{{colors.surface_container_low.dark.hex}}',
  base03 = '{{colors.outline_variant.dark.hex}}',
  base04 = '{{colors.on_surface_variant.dark.hex}}',
  base05 = '{{colors.on_surface.dark.hex}}',
  base06 = '{{colors.inverse_on_surface.dark.hex}}',
  base07 = '{{colors.surface_bright.dark.hex}}',

  base08 = '{{colors.error.dark.hex}}',
  base09 = '{{colors.tertiary.dark.hex}}',
  base0A = '{{colors.secondary.dark.hex}}',
  base0B = '{{colors.primary.dark.hex}}',
  base0C = '{{colors.tertiary_container.dark.hex}}',
  base0D = '{{colors.primary_container.dark.hex}}',
  base0E = '{{colors.secondary_container.dark.hex}}',
  base0F = '{{colors.error_container.dark.hex}}',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.dark.hex}}',
  fg = '{{colors.background.dark.hex}}',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.on_tertiary_container.dark.hex}}',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.dark.hex}}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.dark.hex}}',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.inverse_primary.dark.hex}}',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '{{colors.surface_container_lowest.dark.hex}}',
  fg = '{{colors.primary.dark.hex}}',
})
