#!/usr/bin/env bash
# Autogenerated by Matugen – do not edit directly.

# Core roles
export MATUGEN_PRIMARY="#ddb9f7"
export MATUGEN_ON_PRIMARY="#402357"

export MATUGEN_SURFACE="#151217"
export MATUGEN_ON_SURFACE="#e8e0e8"

export MATUGEN_ACCENT="#d1c1d9"
export MATUGEN_ON_ACCENT="#372c3f"
