#!/usr/bin/env bash
# Autogenerated by Matugen – do not edit directly.

# Core roles
export MATUGEN_PRIMARY="#efbf6d"
export MATUGEN_ON_PRIMARY="#422c00"

export MATUGEN_SURFACE="#17130b"
export MATUGEN_ON_SURFACE="#ece1d4"

export MATUGEN_ACCENT="#dbc3a1"
export MATUGEN_ON_ACCENT="#3c2e16"
