#!/usr/bin/env bash
# Autogenerated by Matugen – do not edit directly.

# Core roles
export MATUGEN_PRIMARY="#ffb4a2"
export MATUGEN_ON_PRIMARY="#561f11"

export MATUGEN_SURFACE="#1a110f"
export MATUGEN_ON_SURFACE="#f1dfdb"

export MATUGEN_ACCENT="#e7bdb3"
export MATUGEN_ON_ACCENT="#442a23"
