# ──────────────────────────────────────────────
# Hypridle configuration
# Handles screen dim, lock, and suspend behavior
# ──────────────────────────────────────────────

general {
    # Enable systemd inhibition during idle
    before_sleep_cmd = $HOME/.config/hypr/scripts/idle-guard.sh lock
    after_sleep_cmd = hyprctl dispatch dpms on
}

# ───────────────
# TIMEOUT STAGES
# ───────────────

# Dim screen after 3 minutes
listener {
    timeout = 180
    on-timeout = hyprshade on dim
    on-resume  = hyprshade off
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = $HOME/.config/hypr/scripts/idle-guard.sh lock
}

# Turn screen off after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# # Send notification before locking (if on battery)
# listener {
#     timeout = 890
#     on-timeout = notify-send -a HyprIdle -u normal "HyprIdle" "💤 System will suspend in 10s..."
#     only_on_battery = true
# }

# # Suspend after 15 minutes (if on battery)
# listener {
#     timeout = 900
#     on-timeout = $HOME/.config/hypr/scripts/idle-guard.sh suspend
#     only_on_battery = true
# }
